/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package codingweek;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.fxml.FXMLLoader;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new WelcomePageViewController());
        loader.setLocation(getClass().getResource("WelcomePageView.fxml"));
        Parent root = loader.load();
        Scene scene = new Scene(root) ;
        scene.getStylesheets().add(getClass().getResource("style.css").toExternalForm());
        
        primaryStage.setTitle("English Project");
        primaryStage.getIcons().add(new Image(getClass().getResourceAsStream("images/logo.png")));
        primaryStage.setScene(scene);
        primaryStage.setMaximized(true);
        primaryStage.show();
    }

    //change les vues en fonction de l'action de l'utilisateur

    public static void changeToCardView(Stage stage,FlashCard flashCard,StackCards stackCards, Card card) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new CardViewController(flashCard,stackCards,card));
        loader.setLocation(App.class.getResource("CardView.fxml"));
        Parent root = loader.load();
        stage.getScene().setRoot(root);
    }

    public static void changeToLearningView(Stage stage, FlashCard flashCard, StackCards stackCards) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new LearningViewController(flashCard, stackCards));
        loader.setLocation(App.class.getResource("LearningView.fxml"));
        Parent root = loader.load();
        stage.getScene().setRoot(root);
    }

    public static void changeToFirstPageView(Stage stage,FlashCard flashCard) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new FirstPageController(flashCard));
        loader.setLocation(App.class.getResource("FirstPageView.fxml"));
        Parent root = loader.load();
        stage.getScene().setRoot(root);
    }

    public static void changeToStackView(Stage stage,FlashCard flashCard, StackCards stackCards ) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new StackViewController(flashCard,stackCards));
        loader.setLocation(App.class.getResource("StackView.fxml"));
        Parent root = loader.load();
        stage.getScene().setRoot(root);
    }

    public static void changeToStatisticsView(Stage stage, FlashCard flashCard) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new StatisticsViewController(flashCard));
        loader.setLocation(App.class.getResource("StatisticsView.fxml"));
        Parent root = loader.load();
        stage.getScene().setRoot(root);
    }

    public static void changeToMultiplayerView(Stage stage, FlashCard flashCard, StackCards stackCards, Player player1, Player player2, Player player3) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new MultiplayerViewController(flashCard, stackCards, player1, player2, player3));
        loader.setLocation(App.class.getResource("MultiplayerView.fxml"));
        Parent root = loader.load();
        stage.getScene().setRoot(root);
    }

    public static void changeToGrammarMenuView(Stage stage) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new GrammarMenuViewController());
        loader.setLocation(App.class.getResource("GrammarMenuView.fxml"));
        Parent root = (Parent) loader.load();
        stage.getScene().setRoot(root);
    }

    public static void changeToGrammarQuestionView(Stage stage, String nameSerie) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new GrammarQuestionViewController(nameSerie));
        loader.setLocation(App.class.getResource("GrammarQuestionView.fxml"));
        Parent root = (Parent) loader.load();
        stage.getScene().setRoot(root);
    }

    public static void changeToToeicPageView(Stage stage) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new ToeicMenuViewController());
        loader.setLocation(App.class.getResource("ToeicMenuView.fxml"));
        Parent root = (Parent) loader.load();
        stage.getScene().setRoot(root);
    }

    public static void changeToToeicPartOntPageView(Stage stage, String nameSerie) throws Exception{
        FXMLLoader loader = new FXMLLoader();
        loader.setController(new ToeicPart1ViewController(nameSerie));
        loader.setLocation(App.class.getResource("ToeicPart1View.fxml"));
        Parent root = (Parent) loader.load();
        stage.getScene().setRoot(root);
    }
}
